
name: frontend_fo_application_streaming
description: Application de streaming

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI et navigation
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # État et gestion des données
  provider: ^6.1.1
  
  # Réseau et API
  http: ^1.1.0
  
  # Stockage sécurisé
  flutter_secure_storage: ^9.0.0
  
  # Sérialisation JSON
  json_annotation: ^4.8.1
  
  # Internationalisation
  intl: ^0.18.1
  
  # Lecteur vidéo - Solution alternative plus stable
  video_player: ^2.8.1
  webview_flutter: ^4.4.2
  
  # Pour les URLs YouTube (alternative à youtube_player_flutter)
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/


# Réinst