name: frontend_fo_application_streaming
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core packages
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.0
  
  # UI packages
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  
  # Video player (choisir l'un des trois)
  webview_flutter: ^4.4.2        # Option 2: WebView pour iframe
  flutter_inappwebview: ^6.0.0   # Option 3: WebView avancé
  youtube_player_flutter: 9.1.1

  
  # Optionnel - pour améliorer l'expérience
  cached_network_image: ^3.3.1   # Pour cacher les images
  url_launcher: ^6.2.4          # Pour ouvrir dans le navigateur


  # Other
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/