# frontend_fo_application_streaming/pubspec.yaml

name: frontend_fo_application_streaming
description: "Application de streaming Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI et Navigation
  cupertino_icons: ^1.0.2
  
  # Gestion d'état
  provider: ^6.1.1
  
  # Réseau et API
  http: ^1.1.0
  dio: ^5.4.0
  
  # Stockage sécurisé
  
  # Lecture vidéo et WebView
  youtube_player_flutter: ^8.1.2
  
  # Images et SVG
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Animations et squelettes
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Sérialisation JSON
  json_annotation: ^4.8.1
  
  # Utilitaires
  intl: ^0.19.0
  
  webview_flutter: ^4.4.2  # Version stable

  url_launcher: ^6.2.1
  flutter_secure_storage: ^9.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Génération de code
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
